### ISSUE TITLE
Adicionar tradução do README.md para inglês

### ISSUE THREAD

**Issue by hideki-lu** [hideki-lu/filty#3]
**[pt-br]**
Para que este projeto possa ser acessível para outras pessoas, é importante que tenha pelo menos uma tradução para inglês dos documentos informativos como o `README.md`.

**[eng]**
In order for this project to be accessible to others, it is important that the project have at least a English translation of the informational documents such as `README.md`.

**Comment by Space-G** [comment]
Eu posso fazer isso

**Comment by hideki-lu** [comment]
Pode realizar, fique a vontade 😁
