### ISSUE TITLE
Separar teste do código fonte.

### ISSUE THREAD

**Issue by Space-G** [hideki-lu/filty#4]
**[pt-br]**

Funções de teste como a `mess_everything` não deveria estar junto do código fonte da biblioteca no diretório /src

**[en]**

Test functions, like `mess_everything`, shouldn't be in the library's source code on the /src directory

**Comment by Marcos-Pimentel** [comment]
Boa noite @hideki-lu , gostaria de trabalhar junto da @Space-G  nessa issue, se possivel.

**Comment by hideki-lu** [comment]
Olá @Marcos-Pimentel , pode sim. Bom desenvolvimento.
