### ISSUE TITLE
Adição de pasta com exemplos de uso da biblioteca

### ISSUE THREAD

**Issue by hideki-lu** [hideki-lu/filty#5]
**[pt-br]**
Atualmente existe um acoplamento no código que foi apontado na issue #4 e que para organizar o projeto é necessária uma refatoração que permita códigos exemplo que oriente novas pessoas que queiram experimentar o projeto e conhecer mais sobre.

**[eng]**
Currently, there is a coupling in the code that was pointed out in issue #4 and to organize the project, a refactoring is necessary that allows example codes that guide new people who want to try out the project and know more about.

**Comment by leoamsena** [comment]
Bom dia @hideki-lu ! Eu e dois amigos do curso de ciência da computação da UFLA gostaríamos de resolver essa issue. Podemos?

**Comment by hideki-lu** [comment]
Olá @leoamsena, podem resolver sim. Obrigado pelo apoio 😁👍

**Comment by Marcos-Pimentel** [comment]
Boa noite, @hideki-lu , eu estou interessado em pegar essa issue, teria como?

**Comment by Space-G** [comment]
@hideki-lu estou meio confusa entre a diferença deste issue e o #4 , seria o #4 apenas a remoção do mess_everything e da main, e esse daqui a recriação do mess_everything e outros exemplos?

**Comment by hideki-lu** [comment]
extamente isso, porque para mim é como se pudesse isolar a função `mess_everything` e deixar dentro da biblioteca, e seria uma alteração. E outra coisa é tornar a mesma função um código de exemplo separado da biblioteca. Consegue visualizar a estrutura?

**Comment by hideki-lu** [comment]
perdão não ter respondido mais cedo @Marcos-Pimentel. No entanto respondi o @leoamsena para resolver esta issue.
