### ISSUE TITLE
Função de desenhar triângulo

### ISSUE THREAD

**Issue by Space-G** [hideki-lu/filty#7]
**[pt-br]**
Acho que pra esta biblioteca uma função de desenhar triângulos seria muito útil.

**[en]**
I think a triangle draw function would be useful in this library.

**Comment by Space-G** [comment]
O que acha @hideki-lu ?

**Comment by hideki-lu** [comment]
acho interessante a proposta e mais adequada colocar como exemplo, seria possível no momento?

**Comment by Space-G** [comment]
Yup, farei.
